// Specializzazioni e nomi delle abilità: allineati al compendio Abilità di call-of-cthulhu-7th-babele-it.
// Combattere, Armi da Fuoco, Lingua, Pilotare, A Distanza e Generico coincidono anche con static/lang/it.json di CoC7.
export const spec = {
  'Art/Craft': 'Arti e Mestieri',
  Fighting: 'Combattere',
  Firearms: 'Armi da Fuoco',
  Kingdom: 'Regno',
  Language: 'Lingua',
  Lore: 'Conoscenze',
  'Natural World': 'Scienze Naturali',
  Pilot: 'Pilotare',
  Ranged: 'A Distanza',
  'Read and Write': 'Leggere e Scrivere',
  Science: 'Scienza',
  Survival: 'Sopravvivenza'
}

// Nomi delle abilità, indicizzati per "specializzazione|nome"
export const skill = {
  '|Accounting': 'Contabilità',
  '|Alienism': 'Alienismo',
  '|Animal Handling': 'Gestione Animali',
  '|Animal Training': 'Ammaestrare Animali',
  '|Anthropology': 'Antropologia',
  '|Appraise': 'Valutare',
  '|Archaeology': 'Archeologia',
  '|Astronomy': 'Astronomia',
  '|Charm': 'Fascino',
  '|Civics': 'Educazione Civica',
  '|Clairvoyance': 'Chiaroveggenza',
  '|Climb': 'Scalare',
  '|Computer Use': 'Informatica',
  '|Credit Rating': 'Valore di Credito',
  '|Cthulhu Mythos': 'Miti di Cthulhu',
  '|Dancing': 'Danza',
  '|Demolitions': 'Demolizioni',
  '|Disguise': 'Camuffare',
  '|Divination': 'Divinazione',
  '|Diving': 'Immersione',
  '|Dodge': 'Schivare',
  '|Drive Auto': 'Guida Auto',
  '|Drive Carriage / Cart': 'Guidare Carrozza / Carretto',
  '|Drive Horse / Oxen': 'Guidare Cavalli / Buoi',
  '|Drive Wagon / Carriage': 'Guidare Carro / Carrozza',
  '|Drive Wagon / Coach': 'Guidare Carro / Diligenza',
  '|Electrical Repair': 'Riparazioni Elettriche',
  '|Electronics': 'Elettronica',
  '|Empire': 'Impero',
  '|Etiquette': 'Etichetta',
  '|Fashion': 'Moda',
  '|Fast Talk': 'Raggirare',
  '|First Aid': 'Primo Soccorso',
  '|Gambling': "Gioco d'Azzardo",
  '|Gaming': 'Giochi',
  '|History': 'Storia',
  '|Hypnosis': 'Ipnosi',
  '|Insight': 'Intuito',
  '|Intimidate': 'Intimidire',
  '|Jump': 'Saltare',
  '|Law': 'Legge',
  '|Library Use': 'Usare Biblioteche',
  '|Listen': 'Ascoltare',
  '|Locksmith': 'Scassinare',
  '|Mechanical Repair': 'Riparazioni Meccaniche',
  '|Medicine': 'Medicina',
  '|Medium': 'Medianità',
  '|Mesmerism': 'Mesmerismo',
  '|Natural Philosophy': 'Filosofia Naturale',
  '|Natural World': 'Scienze Naturali',
  '|Navigate': 'Orientarsi',
  '|Occult': 'Occultismo',
  '|Operate Heavy Machinery': 'Manovrare Macchinari Pesanti',
  '|Persuade': 'Persuadere',
  '|Psychic': 'Poteri Psichici',
  '|Psychoanalysis': 'Psicanalisi',
  '|Psychology': 'Psicologia',
  '|Psychometry': 'Psicometria',
  '|Read Lips': 'Leggere le Labbra',
  '|Reassure': 'Rassicurare',
  '|Religion': 'Religione',
  '|Repair': 'Riparare',
  '|Repair/Devise': 'Riparare/Inventare',
  '|Reputation': 'Reputazione',
  '|Ride Horse': 'Montare a Cavallo',
  '|Ride': 'Cavalcare',
  '|Rope Use': 'Uso delle Corde',
  '|Sleight of Hand': 'Rapidità di Mano',
  '|Spot Hidden': 'Individuare',
  '|Status': 'Status',
  '|Stealth': 'Furtività',
  '|Swim': 'Nuotare',
  '|Tactics': 'Tattica',
  '|Telekinesis': 'Telecinesi',
  '|Track': 'Seguire Tracce',
  '|Trap': 'Trappole',
  '|Write Language': 'Scrivere Lingue',

  'Art/Craft|Acting': 'Recitazione',
  'Art/Craft|Apiarist': 'Apicoltura',
  'Art/Craft|Art Appreciation': "Critica d'Arte",
  'Art/Craft|Bas-relief': 'Bassorilievo',
  'Art/Craft|Bellringing': 'Suonare le Campane',
  'Art/Craft|Blacksmithing': 'Forgiatura',
  'Art/Craft|Bone and Horn Worker': 'Lavorazione di Osso e Corno',
  'Art/Craft|Bowyer': 'Costruzione di Archi',
  'Art/Craft|Brewer': 'Birrificazione',
  'Art/Craft|Carpentry': 'Carpenteria',
  'Art/Craft|Cartographer': 'Cartografia',
  'Art/Craft|Chalk Art': 'Disegno a Gesso',
  'Art/Craft|Cobbler': 'Calzoleria',
  'Art/Craft|Cooking': 'Cucina',
  'Art/Craft|Cooper': 'Costruzione di Botti',
  'Art/Craft|Dancer': 'Danza',
  'Art/Craft|Domestic Service': 'Servizio Domestico',
  'Art/Craft|Embroidery': 'Ricamo',
  'Art/Craft|Farmer': 'Agricoltura',
  'Art/Craft|Fine Art': 'Belle Arti',
  'Art/Craft|Fletcher': 'Costruzione di Frecce',
  'Art/Craft|Forgery': 'Falsificare',
  'Art/Craft|Fresco': 'Affresco',
  'Art/Craft|Jeweler': 'Oreficeria',
  'Art/Craft|Leather Worker': 'Lavorazione del Cuoio',
  'Art/Craft|Literature': 'Letteratura',
  'Art/Craft|Metal Worker': 'Lavorazione dei Metalli',
  'Art/Craft|Mosaic': 'Mosaico',
  'Art/Craft|Musician': 'Musica',
  'Art/Craft|Orate': 'Oratoria',
  'Art/Craft|Painting': 'Pittura',
  'Art/Craft|Photography': 'Fotografia',
  'Art/Craft|Poetry': 'Poesia',
  'Art/Craft|Potions': 'Pozioni',
  'Art/Craft|Pottery': 'Ceramica',
  'Art/Craft|Sculpture': 'Scultura',
  'Art/Craft|Sewing': 'Cucito',
  'Art/Craft|Short Hand': 'Stenografia',
  'Art/Craft|Singer': 'Canto',
  'Art/Craft|Smith': 'Mestiere del Fabbro',
  'Art/Craft|Stonemason': 'Lavorazione della Pietra',
  'Art/Craft|Sweep': 'Spazzacamino',
  'Art/Craft|Technical Drawing': 'Disegno Tecnico',
  'Art/Craft|Typing': 'Dattilografia',
  'Art/Craft|Weaver': 'Tessitura',
  'Art/Craft|Woodworker': 'Lavorazione del Legno',
  'Art/Craft|Writing': 'Scrittura',

  'Fighting|Axe': 'Ascia',
  'Fighting|Brawl': 'Mischia',
  'Fighting|Chainsaw': 'Motosega',
  'Fighting|Flail': 'Flagello',
  'Fighting|Garrote': 'Garrota',
  'Fighting|Lance': 'Lancia da Cavaliere',
  'Fighting|Mace': 'Mazza',
  'Fighting|Shield': 'Scudo',
  'Fighting|Shovel': 'Pala',
  'Fighting|Spear': 'Lancia',
  'Fighting|Staff': 'Bastone',
  'Fighting|Sword': 'Spada',
  'Fighting|Throw': 'Lanciare',
  'Fighting|Whip': 'Frusta',

  'Firearms|Artillery': 'Artiglieria',
  'Firearms|Bow': 'Arco',
  'Firearms|Flamethrower': 'Lanciafiamme',
  'Firearms|Handgun': 'Pistola',
  'Firearms|Heavy Weapons': 'Armi Pesanti',
  'Firearms|Machine Gun': 'Mitragliatrice Pesante',
  'Firearms|Musket': 'Moschetto',
  'Firearms|Pistol': 'Pistola ad Avancarica',
  'Firearms|Rifle/Blunderbuss': 'Fucile/Trombone',
  'Firearms|Rifle/Shotgun': 'Fucile/Fucile a Pompa',
  'Firearms|Submachine Gun': 'Mitraglietta',

  'Kingdom|Other': 'Altro',
  'Kingdom|Own': 'Proprio',

  'Language|Czech': 'Ceco',
  'Language|Dutch': 'Olandese',
  'Language|English': 'Inglese',
  'Language|French': 'Francese',
  'Language|German,': 'Tedesco',
  'Language|Latin': 'Latino',
  'Language|Other': 'Altra',
  'Language|Own': 'Propria',
  'Language|Polish': 'Polacco',
  'Language|Russian': 'Russo',
  'Language|Swahili': 'Swahili',
  'Language|Yoruba': 'Yoruba',
  'Language|Zulu': 'Zulu',

  'Pilot|Aircraft': 'Aereo',
  'Pilot|Balloon': 'Mongolfiera',
  'Pilot|Boat': 'Imbarcazioni',

  'Ranged|Bow': 'Arco',
  'Ranged|Crossbow': 'Balestra',
  'Ranged|Sling': 'Fionda',
  'Ranged|War Engine': 'Macchine da Guerra',

  'Read and Write|Latin': 'Latino',

  'Science|Architecture': 'Architettura',
  'Science|Arithmetic': 'Aritmetica',
  'Science|Astrology': 'Astrologia',
  'Science|Astronomy': 'Astronomia',
  'Science|Augury': 'Aruspicina',
  'Science|Biology': 'Biologia',
  'Science|Botany': 'Botanica',
  'Science|Chemistry': 'Chimica',
  'Science|Cryptography': 'Crittografia',
  'Science|Dialectic': 'Dialettica',
  'Science|Engineering': 'Ingegneria',
  'Science|Forensics': 'Forense',
  'Science|Geography': 'Geografia',
  'Science|Geology': 'Geologia',
  'Science|Geometry': 'Geometria',
  'Science|Grammar': 'Grammatica',
  'Science|Mathematics': 'Matematica',
  'Science|Metallurgy': 'Metallurgia',
  'Science|Meteorology': 'Meteorologia',
  'Science|Music': 'Musica',
  'Science|Pharmacy': 'Farmacia',
  'Science|Philosophy/Religion': 'Filosofia/Religione',
  'Science|Physics': 'Fisica',
  'Science|Rhetoric': 'Retorica',
  'Science|Zoology': 'Zoologia',

  'Survival|Sea': 'Mare',
  'Survival|Street': 'Strada'
}

export const occupation = {
  Accountant: 'Contabile',
  Acrobat: 'Acrobata',
  'Actor, Film': 'Attore cinematografico',
  'Actor, Stage': 'Attore teatrale',
  'Actor, Stage and Radio': 'Attore di teatro e radio',
  Adventuress: 'Avventuriera',
  'Agency Detective': "Detective d'agenzia",
  Alienist: 'Alienista',
  'Animal Trainer': 'Addestratore di animali',
  Antiquarian: 'Antiquario',
  'Antique Dealer': "Mercante d'antiquariato",
  Archaeologist: 'Archeologo',
  Architect: 'Architetto',
  Aristocrat: 'Aristocratico',
  Artist: 'Artista',
  Assassin: 'Assassino',
  'Asylum Attendant': 'Infermiere di manicomio',
  Athlete: 'Atleta',
  Author: 'Scrittore',
  Aviator: 'Aviatore',
  'Bank Robber': 'Rapinatore di banche',
  Barmaid: 'Cameriera di taverna',
  Barman: 'Oste',
  Bartender: 'Barista',
  'Beat Cop': 'Poliziotto di quartiere',
  Beggar: 'Mendicante',
  'Big Game Hunter': 'Cacciatore di grossa selvaggina',
  Blacksmith: 'Fabbro',
  'Board School Teacher': 'Maestro di scuola pubblica',
  'Book Dealer': 'Libraio',
  Bootlegger: 'Contrabbandiere di alcolici',
  'Bounty Hunter': 'Cacciatore di taglie',
  Boxer: 'Pugile',
  Brigand: 'Brigante',
  Burglar: 'Scassinatore',
  Butler: 'Maggiordomo',
  Cabbie: 'Vetturino',
  Carpenter: 'Carpentiere',
  'Cat Burglar': 'Ladro acrobata',
  Chauffeur: 'Autista privato',
  'Chimney Sweep': 'Spazzacamino',
  Clergy: 'Ecclesiastico',
  'Clergy, Member Of The': 'Membro del clero',
  Cleric: 'Chierico',
  Clerk: 'Impiegato',
  'Computer Programmer': 'Programmatore',
  'Computer Technician': 'Tecnico informatico',
  'Confidence Trickster': 'Truffatore',
  Conman: 'Imbroglione',
  'Consulting Detective': 'Investigatore consulente',
  Counterfeiter: 'Falsario',
  'Cowboy/girl': 'Cowboy/cowgirl',
  Craftspeople: 'Artigiani',
  Craftsperson: 'Artigiano',
  Criminal: 'Criminale',
  'Criminal (freelance/solo)': 'Criminale (indipendente)',
  'Criminal, (“Swell-mob”) Member Of Street Gang': 'Criminale, membro di una banda elegante («Swell-mob»)',
  'Criminal, Con Artist (“Shofulman”)': 'Criminale, spacciatore di monete false («Shofulman»)',
  'Criminal, Confidence Trickster (“Magsman”)': 'Criminale, truffatore («Magsman»)',
  'Criminal, Footpad': 'Criminale, rapinatore di strada',
  'Criminal, Generic (“Gonoph”)': 'Criminale, generico («Gonoph»)',
  'Criminal, Housebreaker (“Cracksman”)': 'Criminale, scassinatore di case («Cracksman»)',
  'Criminal, Lockpicker (“Screwsman”)': 'Criminale, apriserrature («Screwsman»)',
  'Criminal, Member Of Street Gang': 'Criminale, membro di una banda di strada',
  'Criminal, Robber (“Rampsman”)': 'Criminale, rapinatore («Rampsman»)',
  'Criminal, Screever': 'Criminale, falsificatore di lettere («Screever»)',
  'Criminal, Swindler (“Macer”)': 'Criminale, baro («Macer»)',
  'Cult Leader': 'Capo di una setta',
  'Cunning Man/Woman': 'Guaritore/guaritrice di villaggio',
  Deprogrammer: 'Deprogrammatore',
  Designer: 'Designer',
  Dilettante: 'Dilettante',
  Diver: 'Palombaro',
  Doctor: 'Dottore',
  'Doctor of Medicine': 'Medico',
  Drifter: 'Vagabondo',
  Driver: 'Autista',
  Editor: 'Redattore',
  'Elected Official': 'Funzionario eletto',
  Electrician: 'Elettricista',
  Engineer: 'Ingegnere',
  Entertainer: 'Intrattenitore',
  'Ex-Military Enlisted/NCO': 'Ex militare, truppa/sottufficiale',
  'Ex-Military Officer': 'Ex ufficiale',
  Exorcist: 'Esorcista',
  Explorer: 'Esploratore',
  'Expressman/Expresswoman': 'Corriere/corriera postale',
  Farmer: 'Agricoltore',
  'Farmer (Free)': 'Agricoltore (libero)',
  'Federal Agent': 'Agente federale',
  Fence: 'Ricettatore',
  Firefighter: 'Vigile del fuoco',
  Fisherman: 'Pescatore',
  'Foreign Correspondent': "Corrispondente dall'estero",
  'Forensic Surgeon': 'Medico legale',
  Forger: 'Contraffattore',
  Gambler: "Giocatore d'azzardo",
  'Gangster, Boss': 'Gangster, boss',
  'Gangster, Underling': 'Gangster, gregario',
  Gentleman: 'Gentiluomo',
  Gentlewoman: 'Gentildonna',
  'Get-Away Driver': 'Autista per la fuga',
  Governess: 'Istitutrice',
  Gravedigger: 'Becchino',
  Greenhorn: 'Pivello',
  Guard: 'Guardia',
  'Gun Moll': 'Pupa del gangster',
  Gunfighter: 'Pistolero',
  Hacker: 'Hacker',
  Healer: 'Guaritore',
  Heretic: 'Eretico',
  Hermit: 'Eremita',
  'Hired Muscle': 'Scagnozzo',
  'Hit Man/Woman': 'Sicario/sicaria',
  Hobo: 'Hobo',
  Hooker: 'Prostituta',
  'Hospital Orderly': 'Inserviente ospedaliero',
  'Household Officer': 'Funzionario di casa nobiliare',
  'Inquiry Agent': 'Agente investigativo',
  Intern: 'Stagista',
  Inventor: 'Inventore',
  'Investigative Journalist': "Giornalista d'inchiesta",
  'Itinerant Worker': 'Lavoratore itinerante',
  Journalist: 'Giornalista',
  Judge: 'Giudice',
  Juggler: 'Giocoliere',
  'Laboratory Assistant': 'Assistente di laboratorio',
  Laborer: 'Operaio',
  Lady: 'Dama',
  'Lady’s Maid': 'Cameriera personale',
  Lawman: 'Tutore della legge',
  Lawyer: 'Avvocato',
  Librarian: 'Bibliotecario',
  Lumberjack: 'Taglialegna',
  Maid: 'Domestica',
  'Man or Woman of God': 'Uomo o donna di Dio',
  Marine: 'Marine',
  Mayor: 'Sindaco',
  Mechanic: 'Meccanico',
  Mercenary: 'Mercenario',
  Merchant: 'Mercante',
  'Military Officer': 'Ufficiale',
  Millwright: 'Costruttore di mulini',
  Miner: 'Minatore',
  Minstrel: 'Menestrello',
  Missionary: 'Missionario',
  Monk: 'Monaco',
  'Mountain Climber': 'Alpinista',
  'Mountain Man or Woman': 'Uomo o donna di montagna',
  'Museum Curator': 'Curatore di museo',
  Musician: 'Musicista',
  'Musician, Middle Class': 'Musicista, ceto medio',
  'Musician, Working Class': 'Musicista, ceto operaio',
  Navvy: 'Sterratore',
  Noble: 'Nobile',
  'Nouveau Riche': 'Nuovo ricco',
  Nun: 'Suora',
  Nurse: 'Infermiere',
  'Nurse, Middle Class': 'Infermiera, ceto medio',
  'Nurse, Working Class': 'Infermiera, ceto operaio',
  Occultist: 'Occultista',
  'Outdoorsman/woman': 'Uomo/donna dei boschi',
  Outlaw: 'Fuorilegge',
  Parapsychologist: 'Parapsicologo',
  Peasant: 'Contadino',
  Pharmacist: 'Farmacista',
  Photographer: 'Fotografo',
  Photojournalist: 'Fotoreporter',
  Physician: 'Medico',
  Pilgrim: 'Pellegrino',
  Pilot: 'Pilota',
  Plumber: 'Idraulico',
  'Police Detective': 'Detective di polizia',
  'Police Officer': 'Agente di polizia',
  'Police Officer, Constable': 'Agente di polizia, agente semplice',
  'Police Officer, Detective': 'Agente di polizia, detective',
  'Policeman (Foot)': 'Poliziotto (a piedi)',
  'Policeman (Mounted)': 'Poliziotto (a cavallo)',
  Politician: 'Politico',
  Priest: 'Sacerdote',
  'Private Investigator': 'Investigatore privato',
  Professor: 'Professore',
  Prospector: 'Cercatore',
  Prostitute: 'Prostituta',
  Psychiatrist: 'Psichiatra',
  Psychoanalyst: 'Psicoanalista',
  Psychologist: 'Psicologo',
  'Pub Landlady': 'Locandiera',
  'Pub Landlord': 'Locandiere',
  Rancher: 'Allevatore',
  Ranger: 'Ranger',
  Reporter: 'Cronista',
  Researcher: 'Ricercatore',
  Sailor: 'Marinaio',
  'Sailor Enlisted/NCO': 'Marinaio, truppa/sottufficiale',
  'Sailor Officer': 'Ufficiale di marina',
  'Sailor, Commercial': 'Marinaio, marina mercantile',
  'Sailor, Naval': 'Marinaio, marina militare',
  Salesperson: 'Venditore',
  'Sans-culotte': 'Sanculotto',
  Scholar: 'Erudito',
  Scientist: 'Scienziato',
  Scout: 'Esploratore militare',
  Secretary: 'Segretario',
  Sergeant: 'Sergente',
  Servant: 'Servitore',
  'Servant (Footman)': 'Servitore (valletto)',
  'Servant (Housemaid)': 'Servitore (cameriera)',
  'Serving Soldier Enlisted/NCO': 'Soldato in servizio, truppa/sottufficiale',
  'Serving Soldier Officer': 'Soldato in servizio, ufficiale',
  'Sex Worker, Middle Class': 'Lavoratrice del sesso, ceto medio',
  'Sex Worker, Working Class': 'Lavoratrice del sesso, ceto operaio',
  Sexton: 'Sagrestano',
  'Shop Keeper': 'Negoziante',
  Shopkeeper: 'Bottegaio',
  'Skill Trader': 'Artigiano specializzato',
  Smuggler: 'Contrabbandiere',
  Soldier: 'Soldato',
  Spy: 'Spia',
  Stonemason: 'Scalpellino',
  'Street Punk': 'Teppista',
  Student: 'Studente',
  Stuntman: 'Stuntman',
  'Taxi Driver': 'Tassista',
  Teacher: 'Insegnante',
  Thug: 'Delinquente',
  'Tribe Member': 'Membro di una tribù',
  Undertaker: 'Impresario di pompe funebri',
  'Uniformed Police Officer': 'Agente di polizia in divisa',
  'Union Activist': 'Sindacalista',
  'Unskilled Laborer': 'Manovale',
  Valet: 'Cameriere personale',
  Waitress: 'Cameriera',
  'Waitress/Waiter': 'Cameriere/cameriera',
  Warrior: 'Guerriero',
  'Warrior (Free)': 'Guerriero (libero)',
  'White-Collar Worker, Clerk/Executive': 'Colletto bianco, impiegato/funzionario',
  'White-Collar Worker, Middle/Senior Manager': 'Colletto bianco, dirigente',
  Woodsman: 'Boscaiolo',
  Wrestler: 'Lottatore',
  Yogi: 'Yogi',
  Zealot: 'Fanatico',
  Zookeeper: 'Guardiano dello zoo'
}

export const archetype = {
  Adventurer: 'Avventuriero',
  Beefcake: 'Fusto',
  'Bon Vivant': 'Bon vivant',
  'Cold Blooded': 'Sangue freddo',
  Dreamer: 'Sognatore',
  Egghead: 'Testa d\'uovo',
  Explorer: 'Esploratore',
  'Femme Fatale': 'Femme fatale',
  'Grease Monkey': 'Smanettone',
  'Hard Boiled': 'Duro',
  Harlequin: 'Arlecchino',
  Hunter: 'Cacciatore',
  Mystic: 'Mistico',
  Outsider: 'Emarginato',
  Rogue: 'Canaglia',
  Scholar: 'Studioso',
  Seeker: 'Cercatore',
  Sidekick: 'Spalla',
  Steadfast: 'Incrollabile',
  Swashbuckler: 'Spadaccino',
  'Thrill Seeker': 'Cercatore di brividi',
  'Two-Fisted': 'Picchiatore'
}

// Ambientazioni: allineate ai nomi delle ere in it.json di CoC7
export const setup = {
  "1920's Setup": ["Configurazione anni '20", "ambientati negli anni '20"],
  "1930's Pulp Setup": ["Configurazione Pulp anni '30", "Pulp ambientati negli anni '30"],
  'Cthulhu Dark Ages Pulp Setup': ['Configurazione Secoli Bui Pulp', 'Pulp dei Secoli Bui'],
  'Cthulhu Dark Ages Setup': ['Configurazione Secoli Bui', 'dei Secoli Bui'],
  'Cthulhu by Gaslight Pulp Setup': ['Configurazione Cthulhu by Gaslight Pulp', 'Pulp di Cthulhu by Gaslight'],
  'Cthulhu by Gaslight Setup': ['Configurazione Cthulhu by Gaslight', 'di Cthulhu by Gaslight'],
  'Down Darker Trails Pulp Setup': ['Configurazione Down Darker Trails Pulp', 'Pulp di Down Darker Trails'],
  'Down Darker Trails Setup': ['Configurazione Down Darker Trails', 'di Down Darker Trails'],
  'Modern Pulp Setup': ['Configurazione Moderno Pulp', 'Pulp di epoca moderna'],
  'Modern Setup': ['Configurazione Moderno', 'di epoca moderna'] ,
  'Regency Cthulhu Pulp Setup': ['Configurazione Regency Cthulhu Pulp', 'Pulp di Regency Cthulhu'],
  'Regency Cthulhu Setup': ['Configurazione Regency Cthulhu', 'di Regency Cthulhu'],
  'Reign Of Terror Setup': ['Configurazione Regno del Terrore', 'del Regno del Terrore']
}

export const personalText = {
  'other skills as academic or personal specialties': 'altre abilità come specializzazioni accademiche o personali',
  'other skills as academic or personal specialties (e.g. a psychiatrist might take Psychoanalysis)': 'altre abilità come specializzazioni accademiche o personali (per esempio uno psichiatra potrebbe scegliere Psicanalisi)',
  'other skills as personal specialties or specialist reading topics': 'altre abilità come specializzazioni personali o argomenti di studio specialistico'
}

export const monetaryName = {
  Aristocracy: 'Aristocrazia'
}

// I manuali citati esistono solo in inglese, o con numeri di pagina diversi in italiano:
// il titolo resta in originale e si segnala che la pagina è quella dell'edizione inglese.
export function description (html, type, name) {
  let out = html.replace(/<p>See the "([^"]*)" page ([^<]*)<\/p>/g, (m, book, page) => `<p>Vedi «${book}», pagina ${page} (edizione inglese)</p>`)
  if (type === 'setup') {
    out = out.replace(/<p>Default setup for [^<]*<\/p>/, `<p>Configurazione predefinita per i personaggi ${setup[name][1]}.</p>`)
  }
  return out
}
